apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          env:
          - name: POSTGRES_DB
            value: artifactory
          - name: POSTGRES_USER
            value: artifactory
          - name: POSTGRES_PASSWORD
            value: password
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-k8s-service
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory-k8s-deployment
spec:
  selector:
    matchLabels:
      app: artifactory-pro-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: artifactory-pro-k8s
        group: artifactory-k8s-demo
    spec:
      securityContext:
        runAsUser: 1030
        fsGroup: 1030
      containers:
      - name: artifactory-pro-k8s
        image: docker.bintray.io/jfrog/artifactory-pro:6.23.13
        env:
        - name: DB_TYPE
          value: postgresql
        - name: DB_USER
          value: artifactory
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: postgresql-k8s-service
        # Make sure to keep the memory java args aligned with the resources definitions
        - name: EXTRA_JAVA_OPTIONS
          value: "-Xms1g -Xmx2g"
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: "/var/opt/jfrog/backup"
          name: artifactory-bkp-volume
      volumes:
      - name: artifactory-bkp-volume
        persistentVolumeClaim:
          claimName: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  labels:
    app: artifactory
    group: artifactory-k8s-demo
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: artifactory-pro-k8s
